#!/usr/bin/env python3
"""
VideoNut File Validator
Validates the integrity and format of files generated by the VideoNut agents
"""
import os
import sys
import re
from pathlib import Path

def validate_truth_dossier(file_path):
    """Validate the truth_dossier.md file"""
    if not os.path.exists(file_path):
        return False, f"File does not exist: {file_path}"
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check for essential sections
    required_sections = ['The Investigation Blueprint', 'The Findings', 'The Angle', 'The Conflict']
    missing_sections = []
    
    for section in required_sections:
        if f'# {section}' not in content and f'## {section}' not in content:
            missing_sections.append(section)
    
    if missing_sections:
        return False, f"Missing required sections: {missing_sections}"
    
    # Check for minimum content length
    if len(content.strip()) < 100:
        return False, "File content too short, may be incomplete"
    
    return True, "Truth Dossier validation passed"

def validate_narrative_script(file_path):
    """Validate the narrative_script.md file"""
    if not os.path.exists(file_path):
        return False, f"File does not exist: {file_path}"
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check for essential narrative elements
    required_elements = ['The Hook', 'The Bridge', 'The Meat', 'The Verdict']
    missing_elements = []
    
    for element in required_elements:
        if element not in content:
            missing_elements.append(element)
    
    if missing_elements:
        return False, f"Missing required narrative elements: {missing_elements}"
    
    # Check for minimum content length
    if len(content.strip()) < 100:
        return False, "File content too short, may be incomplete"
    
    return True, "Narrative Script validation passed"

def validate_master_script(file_path):
    """Validate the master_script.md file"""
    if not os.path.exists(file_path):
        return False, f"File does not exist: {file_path}"
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Look for the expected format: [NARRATION: "..."] [VISUAL: Description. [Source: URL or MANUAL]]
    narration_pattern = r'\[NARRATION:.*?\]'
    visual_pattern = r'\[VISUAL:.*?\]'
    
    narration_matches = re.findall(narration_pattern, content)
    visual_matches = re.findall(visual_pattern, content)
    
    if len(narration_matches) == 0:
        return False, "No narration blocks found in expected format [NARRATION: \"...\"]"
    
    if len(visual_matches) == 0:
        return False, "No visual blocks found in expected format [VISUAL: ...]"
    
    if len(content.strip()) < 100:
        return False, "File content too short, may be incomplete"
    
    return True, f"Master Script validation passed ({len(narration_matches)} narration blocks, {len(visual_matches)} visual blocks)"

def validate_asset_manifest(file_path):
    """Validate the asset_manifest.md file"""
    if not os.path.exists(file_path):
        return False, f"File does not exist: {file_path}"
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Look for asset entries (should contain URLs or file references)
    url_pattern = r'https?://[^\s<>"{}|\\^`\[\]]+'
    asset_pattern = r'(\[.*?\])|(\*\*.*?\*\*)'  # Markdown links or bold text
    
    url_matches = re.findall(url_pattern, content)
    asset_matches = re.findall(asset_pattern, content)
    
    if len(url_matches) == 0 and len(asset_matches) == 0:
        return False, "No assets or URLs found in manifest"
    
    if len(content.strip()) < 10:
        return False, "File content too short, may be incomplete"
    
    return True, f"Asset Manifest validation passed ({len(url_matches)} URLs found)"

def validate_project_directory(project_dir):
    """Validate the entire project directory structure"""
    results = {}
    
    # Define expected files
    expected_files = {
        'truth_dossier.md': validate_truth_dossier,
        'narrative_script.md': validate_narrative_script,
        'master_script.md': validate_master_script,
        'asset_manifest.md': validate_asset_manifest
    }
    
    for filename, validator in expected_files.items():
        file_path = os.path.join(project_dir, filename)
        is_valid, message = validator(file_path)
        results[filename] = (is_valid, message)
    
    return results

def main():
    if len(sys.argv) < 2:
        print("Usage: python file_validator.py <project_directory> [specific_file]")
        print("Example: python file_validator.py ./Projects/my_project")
        print("Example: python file_validator.py ./Projects/my_project truth_dossier.md")
        sys.exit(1)
    
    project_dir = sys.argv[1]
    specific_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    if not os.path.exists(project_dir):
        print(f"❌ Project directory does not exist: {project_dir}")
        sys.exit(1)
    
    print(f"🔍 Validating VideoNut project: {project_dir}")
    print("-" * 50)
    
    if specific_file:
        # Validate specific file
        validators = {
            'truth_dossier.md': validate_truth_dossier,
            'narrative_script.md': validate_narrative_script,
            'master_script.md': validate_master_script,
            'asset_manifest.md': validate_asset_manifest
        }
        
        if specific_file in validators:
            file_path = os.path.join(project_dir, specific_file)
            is_valid, message = validators[specific_file](file_path)
            
            status = "✅" if is_valid else "❌"
            print(f"{status} {specific_file}: {message}")
            
            if not is_valid:
                sys.exit(1)
        else:
            print(f"❌ Unknown file type: {specific_file}")
            print("Supported files: truth_dossier.md, narrative_script.md, master_script.md, asset_manifest.md")
            sys.exit(1)
    else:
        # Validate entire project
        results = validate_project_directory(project_dir)
        
        all_valid = True
        for filename, (is_valid, message) in results.items():
            status = "✅" if is_valid else "❌"
            print(f"{status} {filename}: {message}")
            if not is_valid:
                all_valid = False
        
        print("-" * 50)
        if all_valid:
            print("🎉 All files validated successfully!")
        else:
            print("❌ Some files failed validation")
            sys.exit(1)

if __name__ == "__main__":
    main()